name: CI
on:
  pull_request:
    branches: [main]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: lint code
        run: |
          pip install pre-commit~=2.13
          make lint

  pip-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install
        run: |
          pip install git+https://github.com/sebastian-sz/mlp-mixer-keras@$GITHUB_HEAD_REF
      - name: Import
        run: python -c "from mlp_mixer import MLPMixer_B16"

  test-output-consistency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: convert weights
        run: |
          pip install tensorflow-cpu==2.5.0
          pip install -e .
          bash scripts/download_all.sh
          bash scripts/convert_all.sh
          make test
